beerlibrary/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^beerlist/', include('beerlist.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

beerlist/urls.py
from django.conf.urls import url
from . import views

app_name = 'beerlist'

urlpatterns = [
    # /beerlist/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /beerlist/541/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),

    # /beerlist/brewery/add/
    url(r'brewery/add/$', views.BreweryCreate.as_view(), name='brewery-add'),

    # /beerlist/brewery/2/
    url(r'brewery/(?P<pk>[0-9]+)/$', views.BreweryUpdate.as_view(), name='brewery-update'),

    # /beerlist/brewery/2/delete/
    url(r'brewery/(?P<pk>[0-9]+)/delete/$', views.BreweryDelete.as_view(), name='brewery-delete'),

    # /beerlist/beer/
    url(r'beer/(?P<pk>[0-9]+)/details$', views.BeerDetailView.as_view(), name='beer-detail'),
]

beerlist/models.py
from django.db import models
from django.urls import reverse


class Brewery(models.Model):
    brewery_name = models.CharField(max_length=200)
    hometown = models.CharField(max_length=200)
    country = models.CharField(max_length=200)
    brewery_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('beerlist:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.brewery_name + ' - ' + self.hometown


class Beer(models.Model):
    brewery = models.ForeignKey(Brewery, on_delete=models.CASCADE)
    beer_name = models.CharField(max_length=200)
    style = models.CharField(max_length=200)
    abv = models.FloatField(max_length=50)
    plato = models.FloatField(max_length=50)
    expired_date = models.DateTimeField(max_length=50)
    is_in_library = models.BooleanField(default=False)

    def __str__(self):
        return self.beer_name

beerlist/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Brewery, Beer


class IndexView(generic.ListView):
    template_name = 'beerlist/index.html'
    context_object_name = 'breweries_list'

    def get_queryset(self):
        return Brewery.objects.all()


class DetailView(generic.DetailView):
    model = Brewery
    template_name = 'beerlist/detail.html'


class BreweryCreate(CreateView):
    model = Brewery
    fields = ['brewery_name', 'hometown', 'country', 'brewery_logo']


class BreweryUpdate(UpdateView):
    model = Brewery
    fields = ['brewery_name', 'hometown', 'country', 'brewery_logo']


class BreweryDelete(DeleteView):
    model = Brewery
    success_url = reverse_lazy('beerlist:index')


class BeerDetailView(generic.DetailView):
    model = Beer
    template_name = 'beerlist/beer_detail.html'

beerlist/templates/beerlist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Beer Library{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Teko' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'beerlist/style.css' %}"/>
</head>
<body>
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>
                <span class="icon-bar" style="background-color: #000000;"></span>
            </button>
            <a class="navbar-brand" href="{% url 'beerlist:index' %}">Beer Library</a>
        </div>

        <!--- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'beerlist:index' %}">
                        <span class="glyphicon glyphicon-oil" aria-hidden="true"></span>&nbsp;
                        Breweries
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'beerlist:index' %}">
                        <span class="glyphicon glyphicon-tint" aria-hidden="true"></span>&nbsp;
                        Beers
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="query" value="">
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'beerlist:brewery-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Brewery
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'beerlist:index' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

beerlist/templates/beerlist/beer_detail.html
{% extends 'beerlist/base.html' %}
<title>{% block title %}Beer Details{% endblock %}</title>

{% block body %}
    <div class="panel panel-default">
        <div class="panel-body">
            <img src="{{ brewery.brewery_logo.url }}" class="img-responsive">

            <h2>{{ beer.beer_name}} - {{ beer.style}}</h2>
            <br><br>
            <table class="table table-bordered">
                <tr>
                  <td>Mark</td>
                  <td>Otto</td>
                </tr>
            </table>

            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

beerlist/templates/beerlist/brewery_form.html
{% extends 'beerlist/base.html' %}
{% block title %}Add a new brewery{% endblock %}
{% block brewery_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'beerlist/form-brewery.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>
{% endblock %}

beerlist/templates/beerlist/detail.html
{% extends 'beerlist/base.html' %}
<title>{% block title %}Brewery Details{% endblock %}</title>

{% block body %}
    <div class="panel panel-default">
        <div class="panel-body">
            <img src="{{ brewery.brewery_logo.url }}" class="img-responsive">

            <h1>{{ brewery.brewery_name }}</h1>

            <ul>
                {% for beer in brewery.beer_set.all %}

                     <a href="{% url 'beerlist:beer-detail' beer.id %}">
                        <li>{{ beer.beer_name}} - {{ beer.style}}</li>
                    </a>

                {% endfor %}
            </ul>

            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
        </div>
    </div>
{% endblock %}

beerlist/templates/beerlist/form-brewery.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

beerlist/templates/beerlist/index.html
{% extends 'beerlist/base.html' %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
    <ul>
        {% for brewery in breweries_list %}

            <a href="{% url 'beerlist:detail' brewery.id %}">
                <img src="{{ brewery.brewery_logo.url }}" class="img-responsive">
            </a>

            <li><a href="{% url 'beerlist:detail' brewery.id %}"> {{ brewery.brewery_name}} </a></li>

            <form action="{% url 'beerlist:brewery-delete' brewery.id %}" method="post" style="display: inline">
                {% csrf_token %}
                <input type="hidden" name="brewery_id" value="{{ brewery.id }}"/>
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>
        {% endfor %}
    </ul>
            </div></div></div></div>
{% endblock %}